---
title: "Statistical Machine Learning: Final Project"
author: "Yicheng Shen"
date: "Nov 24, 2024"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = F, message = F)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "75%", fig.align = 'center')
```

```{r}
library(quantmod)
library(rvest)
library(tidyquant)

# Pull real-time stock data
stocks <- c("AAPL", "MSFT", "GOOG")
stock_data <- tq_get(stocks, get = "stock.prices", from = Sys.Date() - 7, to = Sys.Date())

stock_data_filtered <- stock_data %>%
  select(symbol, date, open, high, low, close, volume)

head(stock_data_filtered)
```


```{r}
# Get S&P 500 stock tickers from Wikipedia
sp500_url <- "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
sp500_table <- read_html(sp500_url) %>%
  html_table(fill = TRUE) %>%
  .[[1]]  # The first table contains the S&P 500 list
sp500_table

Nasdaq100_url <- "https://en.wikipedia.org/wiki/Nasdaq-100#Components"
Nasdaq_info <- read_html(Nasdaq100_url) %>%
  html_table(fill = TRUE) %>%
  .[[5]]  # The fifth table
```


```{r}
write.csv(tq_get(sp500_table$Symbol, get = "stock.prices", from = Sys.Date()-1, to = Sys.Date()), 
          file = "S&P500_all.csv")

write.csv(tq_get(Nasdaq_info$Symbol, get = "stock.prices", from = Sys.Date()-1, to = Sys.Date()), 
          file = "Nasdaq100_all.csv")
```

```{r}
tq_get("GLD", get = "stock.prices", from = Sys.Date()-1, to = Sys.Date() )
```

```{r}
tq_get(c("TSLA","AAPL"),from = '2000-01-01',to = Sys.Date(), get = 'stock.prices') %>%
        ggplot(aes(x=date,y=close,color=symbol)) + geom_line()+
        labs(x="", y="Daily Investment Worth",color="Stock", title = "A One-dollar Investment in Your Specified Stocks")+
        # geom_hline(yintercept= input$target_value,color="black",size = 0.5,alpha=0.5) +
        theme(legend.position="right",plot.title = element_text(hjust = 0.5)) +  theme_economist()
```

```{r}
SP500 = tq_get("SPY", get = "stock.prices", from = Sys.Date()-365*20, to = Sys.Date()) 
SP500$difference = c(0,diff(SP500$close, lag = 1))
SP500$perc_change = c(NA, diff(SP500$close) / head(SP500$close, -1) * 100)

SP500 %>% mutate(perc_change = abs(diff(close)/lag(close)*100)) %>%
ggplot(aes(date,perc_change )) +geom_line()

ggplot(SP500, aes(date, perc_change)) +geom_line()


SP500 %>% mutate(perc_change = diff(close)/lag(close)*100) %>% filter(abs(perc_change) > 10)

```

